typeidea/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.contrib.sitemaps import views as sitemap_views
from django.conf.urls.static import static

from typeidea.custom_site import custom_site
from blog.views import (
    post_list, post_detail, PostDetailView, 
    PostListView, IndexView, CategoryView, 
    TagView, SearchView, AuthorView
)
from config.views import LinkListView
from comment.views import CommentView
from blog.rss import LatestPostsFeed
from blog.sitemap import PostSitemap

from typeidea.api import api

# from config.views import links

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("admin/", custom_site.urls),

    path("", IndexView.as_view(), name="index"),
    path("category/<int:category_id>/", CategoryView.as_view(), name="category-list"),
    path("tag/<int:tag_id>/", TagView.as_view(), name="tag-list"),
    path("post/<int:post_id>.html", PostDetailView.as_view(), name="post-detail"),   #pk,主键查询
    path("search/", SearchView.as_view(), name="search"),
    path("author/<int:owner_id>/", AuthorView.as_view(), name="author"),
    path("links/", LinkListView.as_view(), name="links"),
    path("comment/", CommentView.as_view(), name="comment"),
    path("rss/", LatestPostsFeed(), name="rss"),
    path("sitemap.xml", sitemap_views.sitemap, {'sitemaps': {'posts': PostSitemap}}),
    path("ckeditor/", include('ckeditor_uploader.urls')),

    path("api/", api.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path('silk/', include('silk.urls', namespace='silk')),
    ] + urlpatterns

comment/models.py
from django.db import models

from blog.models import Post

# Create your models here.

class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    # target = models.ForeignKey(Post, verbose_name="评论目标", on_delete=models.PROTECT)
    target = models.CharField(max_length=100, verbose_name="评论目标url")
    content = models.CharField(max_length=2000, verbose_name="内容")
    nickname = models.CharField(max_length=50, verbose_name="昵称")
    website = models.URLField(verbose_name="网站")
    email = models.EmailField(verbose_name="邮箱")
    
    status = models.PositiveIntegerField(
        default=STATUS_NORMAL,
        choices=STATUS_ITEMS,
        verbose_name="状态"
    )
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    @classmethod
    def get_by_target(cls, target):
        """
        获取评论
        """
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL).order_by('-created_time')

    class Meta:
        verbose_name = verbose_name_plural = "评论"

comment/forms.py
from django import forms
import mistune

from .models import Comment


class CommentForm(forms.ModelForm):
    """
    评论表单
    """
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'whidth: 60%;'}),
        error_messages={'required': '请输入昵称'}
    )
    email = forms.EmailField(
        label='邮箱',
        max_length=50,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'style': 'whidth: 60%;'}),
        error_messages={'required': '请输入邮箱'}
    )
    website = forms.URLField(
        label='网站',
        max_length=100,
        widget=forms.URLInput(attrs={'class': 'form-control', 'style': 'whidth: 60%;'}),
        required=False
    )
    content = forms.CharField(
        label='内容',
        max_length=500,
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 6, 'cols': 60}),
        error_messages={'required': '请输入内容'}
    )

    def clean_content(self):
        """
        验证评论内容
        """
        content = self.cleaned_data['content']
        if len(content) < 5:
            raise forms.ValidationError('内容太短')
        content = mistune.markdown(content)
        return content
    

    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

comment/views.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from .forms import CommentForm

# Create your views here.

class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        target = request.POST.get('target')
        if form.is_valid():
            instance = form.save(commit=False)
            instance.target = target
            instance.save()
            succeeded = True
            return redirect(target)
        else:
            succeeded = False

        context = {
              "succeed": succeeded,
              "form": form,
              "target": target,
        }
        return self.render_to_response(context)

typeidea/themes/bootstrap/templates/comment/block.html
<hr>
<div class="comment">
    <form class="form-group" action="{% url 'comment' %}" method="post">
        {% csrf_token %}
        <input name="target" type="hidden" value="{{ target }}" />
        {{ comment_form }}
        <button type="submit" class="btn btn-primary">提交</button>
    </form>

    <!-- 评论列表 -->
    <ul class="list-group">
        {% for comment in comment_list %}
        <li class="list-group-item">
            <div class="nickname">
                <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                <span>{{ comment.created_time }}</span>
            </div>
            <div class="comment-content">
                {% autoescape off %}
                {{ comment.content }}
                {% endautoescape %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

typeidea/themes/bootstrap/templates/comment/result.html
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>评论结果页</title>
        <style>
            .result {
                text-align: center;
                width: 40%;
                margin: 0 auto;
            }
            .errorlist {
                list-style-type: none;
            }
        </style>
    </head>
    <body>
        <div class="result">
            {% if succeed %}
                评论成功！
                <a href="{{ target }}">返回</a>
            {% else %}
                <ul class="errorlist">
                    {% for field, message in form.errors.items %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                <a href="javascript:history.go(-1)">返回</a>
            {% endif %}
        </div>
    </body>
</html>